src/
  constants/
    navItems.js
  components/
    layout/
      AppShell.jsx
      Sidebar.jsx
      Topbar.jsx
    common/
      CollapsibleSection.jsx
      PageFrame.jsx
  pages/
    company/CompanyListPage.jsx
    company/CompanyForm.jsx
    inventory/ItemList.jsx
    inventory/ItemForm.jsx
    sales/CustomerList.jsx
    sales/SaleOrderList.jsx
    purchase/VendorList.jsx
    purchase/PurchaseOrderList.jsx
    bank/BankList.jsx
    bank/BankForm.jsx
    misc/ComingSoon.jsx
  router/
    ContentRouter.jsx
  main.jsx
